import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SynergyAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black w-screen h-screen flex flex-col justify-center items-center text-white gap-1'>
        <h1 className='text-4xl'>SynergyAI.io</h1>
        <h2 className='text-xl'>Coming soon</h2>
      </main>
    </>
  )
}
